# Generated by Django 4.0.4 on 2022-05-05 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('streetaddress', models.TextField()),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('Zipcode', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.IntegerField()),
                ('status', models.CharField(choices=[('Unshipped', 'Unshipped'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('RefundApplicable', 'RefundApplicable'), ('Complete', 'Complete'), ('Shipped', 'Shipped')], default='Unshipped', max_length=50)),
                ('orderDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('available_count', models.IntegerField()),
                ('category', models.ManyToManyField(to='store.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Failed', 'Failed'), ('Unpaid', 'Unpaid'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Declined', 'Declined'), ('Settling', 'Settling'), ('Settled', 'Settled'), ('Cancelled', 'Cancelled'), ('Abandoned', 'Abandoned'), ('Refunded', 'Refunded')], default='Unshipped', max_length=50)),
                ('amount', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Blocked', 'Blocked'), ('Banned', 'Banned'), ('Archived', 'Archived'), ('Unkown', 'Unkown'), ('Compromised', 'Compromised')], default='Active', max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
