# Generated by Django 4.0.4 on 2022-05-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_customer_s_cart_account_remove_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s_cart',
            name='cart_no',
        ),
    ]
