# Generated by Django 4.0.4 on 2022-05-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_s_cart_cart_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='s_cart',
            name='cart_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
