# Generated by Django 4.0.4 on 2022-05-09 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_address_order_scart'),
        ('store', '0011_rename_cart_no_s_cart_cart_id'),
    ]

    operations = [
    ]
