# Generated by Django 4.0.4 on 2022-05-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_merge_20220509_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address',
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.ManyToManyField(blank=True, to='store.address'),
        ),
    ]
