# Generated by Django 4.0.4 on 2022-05-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_merge_20220509_0610'),
        ('store', '0013_remove_account_address_address_account'),
    ]

    operations = [
    ]
