# Generated by Django 4.0.4 on 2022-05-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_address_streetaddress_address_addressline1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='AddressLine1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
